id: P008152
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00EGS1018179
  title: བཻ་རོའི་སྒྲུབ་ཕུག་ངོ་སྤྲོད་མདོར་བསྡུས།
  author: ''
  volumes:
    abf26130f6924a5aa27c16ac874b9dcf:
      image_group_id: I1GS1644
      title: Volume 1 of
      volume_number: 1
      total_pages: 27
      base_file: v001.txt
