id: P008152
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1018179
  title: བཻ་རོའི་སྒྲུབ་ཕུག་ངོ་སྤྲོད་མདོར་བསྡུས།
  author: ''
  volumes:
    f7fcf11e9d7f4c81a3ed0b69b3ad479f:
      image_group_id: I1GS1644
      title: ''
      volume_number: 1
      total_pages: 27
ebook_metadata:
  title: བཻ་རོའི་སྒྲུབ་ཕུག་ངོ་སྤྲོད་མདོར་བསྡུས།
  author: ''
  sku: P008152
  cover: cover.jpg
  layers:
  - pagination
