id: I5491E79E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:20:58+00:00'
last_modified: '2022-06-09T04:51:59.967487+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1018179
  title: བཻ་རོའི་སྒྲུབ་ཕུག་ངོ་སྤྲོད་མདོར་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    47D7:
      image_group_id: I1GS1644
      title: Volume 1 of
      total_pages: 27
      order: 1
      base_file: 47D7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
